# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025      GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

name: Build only GCC 16 Image

on:
  push:
    branches: [ ci-trigger ]
  pull_request:
    branches: [ ci-trigger ]
  workflow_dispatch:  # Allows manual trigger via GitHub UI

permissions:
  contents: read
  packages: write  # Required to push to GHCR

jobs:
  gcc16:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.gcc16
          push: true
          tags: ghcr.io/${{ github.repository }}/gcc16
